# Madthreading Travis CI file

# These use container-based images (faster boot) and Ubuntu 14.04 LTS
sudo: false
dist: trusty

# C++ language
language: cpp

# The apt packages here install our compiled code dependencies.
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-5
                      - g++-5
                      - build-essential
                      - cmake
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig
          env:
              - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5)"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-6
                      - g++-6
                      - build-essential
                      - cmake
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig
          env:
              - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6)"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-7
                      - g++-7
                      - build-essential
                      - cmake
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig
          env:
              - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7)"
        

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
    - mkdir -p build-madthreading/release
    - cd build-madthreading/release
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/madthreading/current \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DENABLE_UNIT_TEST=ON \
        -DUSE_TBB=ON -DUSE_OPENMP=ON -DUSE_TCMALLOC=OFF -DBUILD_CXXSTD=14 \
        -DGENERATE_PYTHON_INTERFACES=OFF ../..
    - make -j4
    - make install -j4

script:
    - ./ex1
    - ./ex2
    - ./ex3a
    - ./ex3b
    - ./ex5
    - ./omp_pi_loop
    - ./omp_pi_spmd_final
    - ./omp_pi_spmd_simple
    - ./omp_pi_task
    - ./pi_cxx11
    - ./pi_lambda_serial
    - ./pi_lambda_tbb
    - ./pi_pthreads
    - ./pi_serial
    - ./pi_tbb
    - ./pi_thread_pool
    - ./pi_thread_pool_tree_1
    - ./pi_thread_pool_tree_2
