# Madthreading Travis CI file

# C++ language
language: cpp
  
# The apt packages here install our compiled code dependencies.
matrix:
  include:
    # macOS
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=$(which clang) && CXX=$(which clang++) && CXXSTD=11 && ENABLE_SSE=OFF && ENABLE_TBB=OFF && ENABLE_OMP=OFF"
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && CXXSTD=14 && ENABLE_SSE=OFF && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && CXXSTD=14 && ENABLE_SSE=OFF && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && CXXSTD=14 && ENABLE_SSE=OFF && ENABLE_TBB=OFF && ENABLE_OMP=OFF"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && CXXSTD=14 && ENABLE_SSE=OFF && ENABLE_TBB=OFF && ENABLE_OMP=OFF"
         

before_install:
    - eval "${MATRIX_EVAL}"
    - DEFAULT_DIR="${PWD}"
    - echo "--> ${PWD}"
    - git clone https://github.com/unittest-cpp/unittest-cpp.git unittest-src
    - mkdir -p unittest-src/build-unittest-cpp
    - cd unittest-src/build-unittest-cpp
    - echo "--> ${PWD}"
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/unittest-cpp \
        -DCMAKE_BUILD_TYPE=Release ${PWD}/..
    - make -j2 
    - make install -j2
    - cd ${DEFAULT_DIR}
    - echo "--> ${PWD}"


install:
    - echo "--> ${PWD}"
    - mkdir -p build-madthreading
    - cd build-madthreading
    - echo "--> ${PWD}"
    - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/madthreading/current \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_EXAMPLES=ON \
        -DBUILD_CXXSTD=${CXXSTD} \
        -DENABLE_UNIT_TEST=ON \
        -DUSE_TBB=${ENABLE_TBB} \
        -DUSE_OPENMP=${ENABLE_OMP} \
        -DUSE_TCMALLOC=OFF \
        -DUSE_SSE=${ENABLE_SSE} \
        -DGENERATE_PYTHON_INTERFACES=OFF \
        -DUnitTest++_ROOT=/${HOME}/unittest-cpp ${PWD}/..
    - grep '^[A-Za-z]' CMakeCache.txt | grep -vi advanced
    - make -j2
    - make install -j2
    
    
script:
    - FILE=ex1 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=ex2 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=ex3a ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=ex3b ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=ex4 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=ex5 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=omp_pi_loop ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=omp_pi_spmd_final ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=omp_pi_spmd_simple ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=omp_pi_task ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_serial ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_cxx11 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_lambda_serial ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_lambda_tbb ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_tbb ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_pthreads ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_thread_pool ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_thread_pool_tree_1 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
    - FILE=pi_thread_pool_tree_2 ; \
                            if [ -f ./${FILE} ]; then ./${FILE} ; fi
