# Madthreading Travis CI file

# These use container-based images (faster boot) and Ubuntu 14.04 LTS
sudo: false
dist: trusty

# C++ language
language: cpp

# The apt packages here install our compiled code dependencies.
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-4.9
                      - g++-4.9
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && ENABLE_TBB=ON && CXXSTD=11"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-5
                      - g++-5
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && ENABLE_TBB=ON && CXXSTD=14"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-6
                      - g++-6
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && ENABLE_TBB=ON && CXXSTD=14"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-7
                      - g++-7
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && ENABLE_TBB=ON && CXXSTD=14"
        - os: linux
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-4.0
                  packages:
                      - clang-4.0
                      - clang++-4.0
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && ENABLE_TBB=OFF && CXXSTD=11"
        - os: linux
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-5.0
                  packages:
                      - clang-5.0
                      - clang++-5.0
                      - build-essential
                      - cmake3
                      - libunittest++-dev
                      - libtbb-dev
                      - libgomp1
                      - swig3.0
          env:
              - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && ENABLE_TBB=OFF && CXXSTD=14"
        

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
    - mkdir -p build-madthreading/release
    - cd build-madthreading/release
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/madthreading/current \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DENABLE_UNIT_TEST=ON \
        -DUSE_TBB=${ENABLE_TBB} -DUSE_OPENMP=ON -DUSE_TCMALLOC=OFF \
        -DBUILD_CXXSTD=${CXXSTD} -DGENERATE_PYTHON_INTERFACES=OFF ../..
    - make -j4
    - make install -j4

script:
    - ./ex1
    - ./ex2
    - ./ex3a
    - ./ex3b
    - ./ex5
    - if [ -f ./omp_pi_loop ]; then ./omp_pi_loop ; fi
    - if [ -f ./omp_pi_spmd_final ]; then ./omp_pi_spmd_final ; fi
    - if [ -f ./omp_pi_spmd_simple ]; then ./omp_pi_spmd_simple ; fi
    - if [ -f ./omp_pi_task ]; then ./omp_pi_task ; fi
    - ./pi_serial
    - ./pi_cxx11
    - ./pi_lambda_serial
    - if [ -f ./pi_lambda_tbb ]; then ./pi_lambda_tbb ; fi
    - if [ -f ./pi_tbb ]; then ./pi_tbb ; fi
    - ./pi_pthreads
    - ./pi_thread_pool
    - ./pi_thread_pool_tree_1
    - ./pi_thread_pool_tree_2
