# Madthreading Travis CI file

language: python

python:
  - "3.5"

# The apt packages here install our compiled code dependencies.
matrix:
  include:
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libgomp1
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && CXXSTD=14 && ENABLE_SSE=ON && ENABLE_TBB=ON && ENABLE_OMP=ON"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libiomp-dev
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && CXXSTD=11 && ENABLE_SSE=ON && ENABLE_TBB=OFF && ENABLE_OMP=ON"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake3
            - libunittest++-dev
            - libtbb-dev
            - libiomp-dev
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && CXXSTD=11 && ENABLE_SSE=ON && ENABLE_TBB=OFF && ENABLE_OMP=ON"
         
         
before_install:
    #- apt-get update
    #- apt-get -y upgrade
    - eval "${MATRIX_EVAL}"
    - export CC=${CC}
    - export CXX=${CXX}
    - export ENABLE_OMP=${ENABLE_OMP}
    - export ENABLE_TBB=${ENABLE_TBB}
    - export ENABLE_SSE=${ENABLE_SSE}
    - export CXXSTD=${CXXSTD}
    - export PYBINPATH=$(dirname $(which python))
    - export PYROOTPATH=$(dirname ${PYBINPATH})
    - export PATH=${PYBINPATH}:${PATH}
    - export CMAKE_PREFIX_PATH=${PYROOTPATH}:${CMAKE_PREFIX_PATH}
    - export PYTHON_VERSION="$(python --version | awk '{print $NF}')"
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    - echo "Python = $(which python) [version ${PYTHON_VERSION}]"
    - echo "PYBINPATH = ${PYBINPATH}"
    - echo "PYROOTPATH = ${PYROOTPATH}"
    - echo "CMAKE_PREFIX_PATH = ${CMAKE_PREFIX_PATH}"

install:
    - env
    - echo "--> ${PWD}"
    - mkdir -p build-project
    - cd build-project
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    - echo "--> ${PWD}"
    - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/madthreading/current
        -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
        -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
        -DBUILD_CXXSTD=${CXXSTD} -DENABLE_UNIT_TEST=ON
        -DUSE_TBB=${ENABLE_TBB} -DUSE_OPENMP=${ENABLE_OMP}
        -DUSE_TCMALLOC=OFF -DUSE_SSE=${ENABLE_SSE}
        -DUSE_ARCH=ON -DPYTHON_EXECUTABLE=$(which python)
        -DBUILD_TESTING=ON -DCTEST_SITE=travis -DCTEST_MODEL=Continous
        -DCTEST_LOCAL_CHECKOUT=ON
        ${PWD}/..
    - grep '^[A-Za-z]' CMakeCache.txt | grep -vi advanced
    #- make VERBOSE=1
    #- make install
    - ctest -S cdash/Stages.cmake -DSTAGES="Build;Test" -DTRIGGER=Test -V --output-on-failure

    
script:
    - echo -e '#!/bin/bash\n\nset -o errexit\n' > ./run_exe.sh
    - echo -e 'RET=0\nif [ -f "./${1}" ]; then\n    ./${1}\n    RET=$?\nfi\n\nexit ${RET}\n' >> ./run_exe.sh
    - chmod +x ./run_exe.sh
    - ./run_exe.sh ex1
    - ./run_exe.sh ex2
    - ./run_exe.sh ex4
    - ./run_exe.sh ex5
    - ./run_exe.sh omp_pi_loop
    - ./run_exe.sh omp_pi_spmd_final
    - ./run_exe.sh omp_pi_spmd_simple
    - ./run_exe.sh omp_pi_task
    - ./run_exe.sh pi_serial
    - ./run_exe.sh pi_cxx11
    - ./run_exe.sh pi_lambda_serial
    - ./run_exe.sh pi_lambda_tbb
    - ./run_exe.sh pi_tbb
    - ./run_exe.sh pi_pthreads
    - ./run_exe.sh pi_thread_pool
